-- The Kingdom: anonymous live poll setup
-- Run this file once in Supabase Dashboard > SQL Editor.
--
-- Privacy model:
--   * No Supabase Auth and no names.
--   * The browser generates a random UUID and keeps it in localStorage.
--   * One current response is stored per browser/device and poll.
--   * Reflection answers never enter this database.
--
-- Security model:
--   * The vote table has RLS enabled and grants no direct table access.
--   * Browser clients can call only three SECURITY DEFINER functions.
--   * The results function returns aggregate counts, never device IDs.

begin;

create table if not exists public.kingdom_poll_votes (
  id bigint generated by default as identity primary key,
  poll_id text not null,
  device_id uuid not null,
  choice text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint kingdom_poll_votes_poll_id_check
    check (poll_id in ('warning', 'drift', 'mercy')),

  constraint kingdom_poll_votes_choice_check
    check (
      (poll_id = 'warning' and choice in ('Yes', 'No', 'Not sure'))
      or
      (poll_id = 'drift' and choice in ('Relationships', 'Private habits', 'Entertainment', 'Attitude'))
      or
      (poll_id = 'mercy' and choice in ('Repent', 'Ask for prayer', 'Change a boundary', 'Talk to a leader'))
    ),

  constraint kingdom_poll_votes_one_vote_per_device
    unique (poll_id, device_id)
);

create index if not exists kingdom_poll_votes_poll_choice_idx
  on public.kingdom_poll_votes (poll_id, choice);

alter table public.kingdom_poll_votes enable row level security;

-- No browser role may read or write the table directly.
revoke all on table public.kingdom_poll_votes from public, anon, authenticated;
revoke usage, select on sequence public.kingdom_poll_votes_id_seq from public, anon, authenticated;

create or replace function public.get_kingdom_poll_results(p_poll_id text)
returns table (
  choice text,
  votes bigint
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if p_poll_id not in ('warning', 'drift', 'mercy') then
    raise exception using
      errcode = '22023',
      message = 'Unknown poll id.';
  end if;

  return query
  with allowed_choices as (
    select option_value, sort_order
    from unnest(
      case p_poll_id
        when 'warning' then array['Yes', 'No', 'Not sure']::text[]
        when 'drift' then array['Relationships', 'Private habits', 'Entertainment', 'Attitude']::text[]
        when 'mercy' then array['Repent', 'Ask for prayer', 'Change a boundary', 'Talk to a leader']::text[]
      end
    ) with ordinality as options(option_value, sort_order)
  )
  select
    allowed_choices.option_value as choice,
    count(votes_table.id)::bigint as votes
  from allowed_choices
  left join public.kingdom_poll_votes as votes_table
    on votes_table.poll_id = p_poll_id
   and votes_table.choice = allowed_choices.option_value
  group by allowed_choices.option_value, allowed_choices.sort_order
  order by allowed_choices.sort_order;
end;
$$;

create or replace function public.submit_kingdom_poll_vote(
  p_poll_id text,
  p_device_id uuid,
  p_choice text
)
returns table (
  choice text,
  votes bigint
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if p_device_id is null then
    raise exception using
      errcode = '22023',
      message = 'A device id is required.';
  end if;

  if not (
    (p_poll_id = 'warning' and p_choice in ('Yes', 'No', 'Not sure'))
    or
    (p_poll_id = 'drift' and p_choice in ('Relationships', 'Private habits', 'Entertainment', 'Attitude'))
    or
    (p_poll_id = 'mercy' and p_choice in ('Repent', 'Ask for prayer', 'Change a boundary', 'Talk to a leader'))
  ) then
    raise exception using
      errcode = '22023',
      message = 'That choice is not valid for this poll.';
  end if;

  insert into public.kingdom_poll_votes (poll_id, device_id, choice)
  values (p_poll_id, p_device_id, p_choice)
  on conflict (poll_id, device_id)
  do update set
    choice = excluded.choice,
    updated_at = now();

  return query
    select results.choice, results.votes
    from public.get_kingdom_poll_results(p_poll_id) as results;
end;
$$;

create or replace function public.clear_kingdom_poll_votes(p_device_id uuid)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if p_device_id is null then
    raise exception using
      errcode = '22023',
      message = 'A device id is required.';
  end if;

  delete from public.kingdom_poll_votes
  where device_id = p_device_id;
end;
$$;

-- Functions are not public by default. Grant only the two browser roles.
revoke all on function public.get_kingdom_poll_results(text) from public;
revoke all on function public.submit_kingdom_poll_vote(text, uuid, text) from public;
revoke all on function public.clear_kingdom_poll_votes(uuid) from public;

grant execute on function public.get_kingdom_poll_results(text) to anon, authenticated;
grant execute on function public.submit_kingdom_poll_vote(text, uuid, text) to anon, authenticated;
grant execute on function public.clear_kingdom_poll_votes(uuid) to anon, authenticated;

comment on table public.kingdom_poll_votes is
  'Anonymous current poll choices for The Kingdom lesson. Reflection answers are never stored here.';
comment on function public.get_kingdom_poll_results(text) is
  'Returns aggregate counts only. It does not expose device identifiers.';
comment on function public.submit_kingdom_poll_vote(text, uuid, text) is
  'Creates or updates one anonymous browser vote per poll, then returns aggregate counts.';
comment on function public.clear_kingdom_poll_votes(uuid) is
  'Removes every current poll vote associated with one browser device id.';

-- Ask PostgREST to refresh its function schema immediately.
notify pgrst, 'reload schema';

commit;
